from __future__ import annotations

import time
from typing import Sequence

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)

# ---------------------------------------------------------------------------
# HTTP Telemetry
# ---------------------------------------------------------------------------
HTTP_REQUESTS_TOTAL = Counter(
    "fleetsense_http_requests_total",
    "Total count of HTTP requests handled by the API",
    ["method", "endpoint", "status"],
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "fleetsense_http_request_duration_seconds",
    "HTTP request latency in seconds",
    ["method", "endpoint"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

# ---------------------------------------------------------------------------
# ML Inference & Data Drift Telemetry
# ---------------------------------------------------------------------------
PREDICTIONS_TOTAL = Counter(
    "fleetsense_predictions_total",
    "Total individual predictions generated by the inference service",
    ["model_version", "status"],
)

PREDICTED_DURATION_HISTOGRAM = Histogram(
    "fleetsense_predicted_duration_minutes",
    "Distribution of predicted trip durations in minutes",
    buckets=(1.0, 3.0, 5.0, 10.0, 15.0, 20.0, 30.0, 45.0, 60.0, 90.0, 120.0),
)

INCOMING_TRIP_DISTANCE_HISTOGRAM = Histogram(
    "fleetsense_incoming_trip_distance_miles",
    "Distribution of incoming trip distances in miles (for data drift tracking)",
    buckets=(0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 15.0, 20.0, 30.0, 50.0),
)

MODEL_LOAD_STATUS = Gauge(
    "fleetsense_model_loaded",
    "Status of the ML inference model (1 if loaded, 0 otherwise)",
    ["model_name"],
)


def record_prediction(
    predicted_duration_minutes: float,
    trip_distance: float,
    model_version: str = "v1",
    status: str = "success",
) -> None:
    """Record metrics for an individual prediction."""
    PREDICTIONS_TOTAL.labels(model_version=model_version, status=status).inc()
    if status == "success":
        PREDICTED_DURATION_HISTOGRAM.observe(predicted_duration_minutes)
        INCOMING_TRIP_DISTANCE_HISTOGRAM.observe(trip_distance)


def record_batch_predictions(
    durations: Sequence[float],
    distances: Sequence[float],
    model_version: str = "v1",
    status: str = "success",
) -> None:
    """Record metrics for a batch of predictions."""
    for duration, distance in zip(durations, distances):
        record_prediction(
            predicted_duration_minutes=duration,
            trip_distance=distance,
            model_version=model_version,
            status=status,
        )


def set_model_status(loaded: bool, model_name: str = "HistGradientBoostingRegressor") -> None:
    """Update the model loading gauge."""
    MODEL_LOAD_STATUS.labels(model_name=model_name).set(1.0 if loaded else 0.0)


def get_latest_metrics() -> tuple[bytes, str]:
    """Return latest Prometheus metrics text and corresponding media type."""
    return generate_latest(), CONTENT_TYPE_LATEST
